### ISSUE TITLE
Possible to integrate with urwid or other TUI frameworks?

### ISSUE THREAD

**Issue by khughitt** [dahlia/iterfzf#25]
Greetings!

I was wondering if you think it would be feasible to integrate iterfzf with something like [urwid](https://github.com/urwid/urwid), so that it could be used in the context of a larger terminal application?

**Comment by dahlia** [comment]
I'm pessimistic about composability/compatibility between TUI frameworks and `fzf`, but if someone are willing to make it that would be great.

**Comment by khughitt** [comment]
No worries. I just thought I would check, in case there was a simple solution. Regardless, thanks for taking the time to create and share iterfzf with the community :)
