### ISSUE TITLE
Release a next version

### ISSUE THREAD

**Issue by MasterTemple** [dahlia/iterfzf#30]
When installing `iterfzf` from [PyPI](https://pypi.org/project/iterfzf/) the `ansi` feature does not exist. I have tried the code from this repository and it works. My assumption is that the PyPI project is not up to date with this repository.

**Comment by dahlia** [comment]
Actually, I've been busy lately and not using Python much, so I've been negligent on the project.  I'm going to release a new version around the weekend.
