### ISSUE TITLE
Extra flags as a parameter feature

### ISSUE THREAD

**Issue by Andrej-Marsic** [dahlia/iterfzf#32]
Hi there,

Wondering if it would make sense to allow for the hack of just passing extra parameters as a string to the iterfzf function.

This way, we could still use some flags if they are not individually implemented.

**Comment by dahlia** [comment]
That's a good idea, I'll look at it positively.

**Comment by dahlia** [comment]
Shipped with [v1.1.0.44.0](https://pypi.org/project/iterfzf/1.1.0.44.0/).
