### ISSUE TITLE
option to use our packaged version of fzf?

### ISSUE THREAD

**Issue by sudomain** [dahlia/iterfzf#37]
Hello,

Thank you for creating iterfzf. Is it possible to use the version of fzf that comes from our package manager, rather than the one that comes bundled with iterfzf? If iterfzf ever becomes unmaintained, users would be stuck on the last version of fzf that was bundled with iterfzf.

**Comment by dahlia** [comment]
`iterfzf()` function has an optional parameter named `executable`, which takes a path to a `fzf` executable to use.  Would it work for you?
