### ISSUE TITLE
Suggestion to bump-up the bundled FZF version.

### ISSUE THREAD

**Issue by Gregory-K** [dahlia/iterfzf#38]
<https://junegunn.github.io/fzf/releases/0.53.0/>
> fzf can now display multi-line items properly.

I find that "Multi-line display" is a reason strong enough for updating the bundled FZF binary.

**Comment by dahlia** [comment]
Released [1.4.0.54.3](https://pypi.org/project/iterfzf/1.4.0.54.3/).

**Comment by Gregory-K** [comment]
thanks for your, as always, prompt response
